global_costmap:
  global_frame: map
  robot_base_frame: zz

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.25

  static_map: true

  obstacle_range: 3.0
  raytrace_range: 3.5

  footprint:
    [[0.2755, -0.2585], [0.2755, 0.2585], [-0.2755, 0.2585], [-0.2755, -0.2585]]
  robot_radius: 0.378

  inflation_radius: 0.5
  cost_scaling_factor: 3.0

  inscribed_radius: 0.378
  circumscribed_radius: 0.378

  map_type: costmap
  observation_sources: scan
  scan:
    {
      sensor_frame: front_laser,
      data_type: LaserScan,
      topic: scan,
      marking: true,
      clearing: true,
      obstacle_range: 2.5,
      raytrace_range: 3.0,
    }
