/**:
  ros__parameters:
    analyzers:
      computers:
        analyzers:
          pc1:
            contains: pc1
            path: pc1
            type: diagnostic_aggregator/GenericAnalyzer
          pc2:
            contains: pc2
            path: pc2
            type: diagnostic_aggregator/GenericAnalyzer
        path: Computers
        type: diagnostic_aggregator/AnalyzerGroup
      motors:
        analyzers:
          base:
            analyzers:
              base:
                contains: base/
                path: Base
                type: diagnostic_aggregator/GenericAnalyzer
              base_twist_mux:
                contains: twist_mux
                path: twist_mux
                type: diagnostic_aggregator/GenericAnalyzer
            path: Base
            type: diagnostic_aggregator/AnalyzerGroup
        path: Actuators
        type: diagnostic_aggregator/AnalyzerGroup
      sensors:
        analyzers:
          joystick:
            contains: joy
            path: Joystick
            type: diagnostic_aggregator/GenericAnalyzer
          laser_front:
            contains: laser_front
            path: Scan Front
            type: diagnostic_aggregator/GenericAnalyzer
          laser_rear:
            contains: laser_rear
            path: Scan Rear
            type: diagnostic_aggregator/GenericAnalyzer
        path: Sensors
        type: diagnostic_aggregator/AnalyzerGroup
    base_path: ''
    pub_rate: 1.0
