/**:
  ros__parameters:
    avg_vel: 0.5
    dynamic_obstacle/inflation_radius: 0.1
    dynamic_obstacle/obstacle_radius: 0.15
    dynamic_obstacle/prediction_forward_time: 0.5
    dynamic_obstacle/sensor_range: 3.0
    fsm/goal_tolerance: 0.2
    fsm/planning_horizon: 1.0
    fsm/replan_time_thresh: 0.5
    fsm/subgoal_drl_mode: 0
    fsm/subgoal_pub_period: 0.5
    fsm/subgoal_tolerance: 0.2
    fsm/use_drl: true
    goal_tolerance: 0.2
    kino_astar/allocate_num: 100000
    kino_astar/check_num: 5
    kino_astar/goal_tolerance: 0.5
    kino_astar/horizon: 100.0
    kino_astar/init_max_tau: 0.8
    kino_astar/lambda_heu: 0.1
    kino_astar/max_acc: 4.0
    kino_astar/max_tau: 0.6
    kino_astar/max_vel: 3.0
    kino_astar/resolution_astar: 0.1
    kino_astar/time_resolution: 0.8
    kino_astar/vel_margin: 0.0
    kino_astar/w_time: 10.0
    max_acc: 0.12
    max_jerk: 4.0
    max_vel: 0.5
    min_vel: 0.08
    obstacle_name: obstacle_dynamic_with_traj
    obstacle_radius: 0.15
    obstacles_inflation: 0.05
    optimization/dist0: 0.5
    optimization/lambda_collision: 1.5
    optimization/lambda_feasibility: 0.1
    optimization/lambda_fitness: 1.0
    optimization/lambda_smooth: 1.0
    optimization/max_acc_: 0.12
    optimization/max_vel: 0.5
    optimization/order_: 3
    optimization/swarm_clearance: 0.1
    optimization_ESDF/dist0: 0.5
    optimization_ESDF/lambda1: 10.0
    optimization_ESDF/lambda2: 5.0
    optimization_ESDF/lambda3: 1.0e-05
    optimization_ESDF/lambda4: 0.01
    optimization_ESDF/lambda5: 1.5
    optimization_ESDF/lambda6: 10.0
    optimization_ESDF/lambda7: 100.0
    optimization_ESDF/max_acc: 4.0
    optimization_ESDF/max_iteration_num1: 2
    optimization_ESDF/max_iteration_num2: 300
    optimization_ESDF/max_iteration_num3: 200
    optimization_ESDF/max_iteration_num4: 200
    optimization_ESDF/max_iteration_time1: 0.0001
    optimization_ESDF/max_iteration_time2: 0.005
    optimization_ESDF/max_iteration_time3: 0.003
    optimization_ESDF/max_iteration_time4: 0.003
    optimization_ESDF/max_vel: 3.0
    optimization_ESDF/order: 3
    plan_manager/control_points_distance: 0.4
    plan_manager/dynamic_obstacle_name: obstacle_dynamic_with_traj
    plan_manager/feasibility_tolerance: 0.05
    plan_manager/local_time_horizon: 3.0
    plan_manager/max_acc: 0.12
    plan_manager/max_jerk: 4.0
    plan_manager/max_vel: 0.5
    plan_manager/use_distinctive_trajs: true
    planning_horizon: 1.0
    planning_time_horizon: 3.0
    robot_radius: 0.629
    sdf_map/frame_id: map
    sdf_map/local_bound_inflate: 0.0
    sdf_map/local_map_margin: 0
    sdf_map/local_update_range_x: 3.0
    sdf_map/local_update_range_y: 3.0
    sdf_map/max_ray_length: 3.0
    sdf_map/min_ray_length: 0.1
    sdf_map/obstacles_inflation: 0.05
    sdf_map/p_hit: 0.52
    sdf_map/p_max: 0.75
    sdf_map/p_min: 0.1
    sdf_map/p_miss: 0.15
    sdf_map/p_occ: 0.7
    sdf_map/show_esdf_time: false
    sdf_map/show_occ_time: false
    sdf_map/use_occ_esdf: true
    sensor_range: 3.0
    subgoal_mode: 0
    subgoal_pub_period: 0.5
    subgoal_tolerance: 0.2
    timed_astar/allocate_num: 10000
    timed_astar/avg_vel: 0.5
    timed_astar/goal_tolerance: 0.2
    timed_astar/max_rot_vel: 0.3
    timed_astar/max_vel: 0.5
    timed_astar/min_vel: 0.08
    timed_astar/num_sample_edge: 10
    timed_astar/obstacle_radius: 0.15
    timed_astar/resolution: 0.1
    timed_astar/robot_radius: 0.629
    timed_astar/safe_time: 1.0
    timed_astar/sensor_range: 3.0
    timed_astar/time_horizon: 3.0
    timed_astar/time_resolution: 0.2
    use_drl: true
