local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05

  obstacle_range: 3.0
  raytrace_range: 3.5

  # footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
  footprint:
    [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
  #robot_radius: 0.105

  inflation_radius: 1.0
  cost_scaling_factor: 3.0

  map_type: costmap
  observation_sources: scan
  scan:
    {
      sensor_frame: base_scan,
      data_type: LaserScan,
      topic: scan,
      marking: true,
      clearing: true,
    }
