/**:
  ros__parameters:
    footprint_angular_fast:
    - - 0.5
      - 0.5
    - - -0.5
      - 0.5
    - - -0.5
      - -0.5
    - - 0.5
      - -0.5
    footprint_angular_slow:
    - - 0.4
      - 0.4
    - - -0.4
      - 0.4
    - - -0.4
      - -0.4
    - - 0.4
      - -0.4
    footprint_linear_fast:
    - - 0.8
      - 0.4
    - - -0.4
      - 0.4
    - - -0.4
      - -0.4
    - - 0.8
      - -0.4
    footprint_linear_slow:
    - - 0.6
      - 0.4
    - - -0.4
      - 0.4
    - - -0.4
      - -0.4
    - - 0.6
      - -0.4
    has_wireless_emstop: true
    marker_type: 11
    odometry_timeout: 1.0
    port: '9100'
    reconnect_attempts: 5
    reconnect_duration: 5
    scale_x: 1.0
    scale_y: 1.0
    scale_z: 1.0
    threshold_angular_fast: 1.0
    threshold_linear_fast: 0.9
    threshold_linear_slow: 0.4
    warn_for_laser_bridged: false
    warn_for_wireless_bridged: false
