/**:
  ros__parameters:
    defaults:
      dcf_overlay:
        604Csub1: '1'
        604Csub2: '24000'
      eds_file: robots/common/Schunk_0_63.dcf
      eds_pkg: cob_hardware_config
      vel_to_device: rint(rad2deg(vel)*250)
    nodes:
    - id: 51
      name: arm_left_1_joint
    - id: 52
      name: arm_left_2_joint
    - id: 53
      name: arm_left_3_joint
    - id: 54
      name: arm_left_4_joint
    - id: 55
      name: arm_left_5_joint
    - id: 56
      name: arm_left_6_joint
    - id: 57
      name: arm_left_7_joint
    sync:
      interval_ms: 10
      overflow: 0
