/**:
  ros__parameters:
    gripper_left_finger_1_joint_position_controller:
      joint: gripper_left_finger_1_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    gripper_left_finger_2_joint_position_controller:
      joint: gripper_left_finger_2_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    joint_group_position_controller:
      joints:
      - gripper_left_finger_1_joint
      - gripper_left_finger_2_joint
      required_drive_mode: 1
      type: position_controllers/JointGroupPositionController
    joint_names:
    - gripper_left_finger_1_joint
    - gripper_left_finger_2_joint
    joint_state_controller:
      publish_rate: 50
      type: joint_state_controller/JointStateController
    joint_trajectory_controller:
      action_monitor_rate: 10
      constraints:
        goal_time: 0.6
        gripper_left_finger_1_joint:
          goal: 0.1
          trajectory: 0.1
        gripper_left_finger_2_joint:
          goal: 0.1
          trajectory: 0.1
        stopped_velocity_tolerance: 0.05
      joints:
      - gripper_left_finger_1_joint
      - gripper_left_finger_2_joint
      required_drive_mode: 7
      state_publish_rate: 25
      stop_trajectory_duration: 0.5
      type: position_controllers/JointTrajectoryController
    max_command_silence: 0.5
