/**:
  ros__parameters:
    joint_group_position_controller:
      joints:
      - torso_2_joint
      - torso_3_joint
      required_drive_mode: 1
      type: position_controllers/JointGroupPositionController
    joint_group_velocity_controller:
      joints:
      - torso_2_joint
      - torso_3_joint
      required_drive_mode: 3
      type: velocity_controllers/JointGroupVelocityController
    joint_names:
    - torso_2_joint
    - torso_3_joint
    joint_state_controller:
      publish_rate: 50
      type: joint_state_controller/JointStateController
    joint_trajectory_controller:
      action_monitor_rate: 10
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        torso_2_joint:
          goal: 0.1
          trajectory: 0.1
        torso_3_joint:
          goal: 0.1
          trajectory: 0.1
      joints:
      - torso_2_joint
      - torso_3_joint
      required_drive_mode: 7
      state_publish_rate: 25
      stop_trajectory_duration: 0.5
      type: position_controllers/JointTrajectoryController
    max_command_silence: 0.5
    torso_2_joint_position_controller:
      joint: torso_2_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    torso_2_joint_velocity_controller:
      joint: torso_2_joint
      required_drive_mode: 3
      type: velocity_controllers/JointVelocityController
    torso_3_joint_position_controller:
      joint: torso_3_joint
      required_drive_mode: 1
      type: position_controllers/JointPositionController
    torso_3_joint_velocity_controller:
      joint: torso_3_joint
      required_drive_mode: 3
      type: velocity_controllers/JointVelocityController
