robot_base_frame: $(arg frame)base_link

update_frequency: 5.0 
publish_frequency: 5.0 

obstacle_range: 10.0
raytrace_range: 15.0

transform_tolerance: 0.25
resolution: 0.05 

footprint: [[-0.25, -0.145], [-0.25, 0.145], [0.25, 0.145], [0.25, -0.145]]
robot_radius: 0.5

map_type: costmap

static_map_layer:
  map_topic: map
  subscribe_to_updates: true

2d_obstacles_layer:
  observation_sources: helios

  helios:
    {
      sensor_frame: $(arg frame)helios_lidar,
      data_type: LaserScan,
      topic: $(arg namespace)helios_points,
      marking: true,
      clearing: true
    }

3d_obstacles_layer: 
  # observation_sources: helios_lidar front_rgbd rear_rgbd rear_left_rgbd rear_right_rgbd
  observation_sources: front_rgbd rear_rgbd rear_left_rgbd rear_right_rgbd

  helios_lidar:
    {
      sensor_frame: $(arg frame)helios_lidar,
      data_type: PointCloud2,
      topic: $(arg namespace)helios_points,
      marking: true,
      clearing: true
    }

  front_rgbd:
    {
      sensor_frame: $(arg frame)front_rgbd_reference_frame,
      data_type: PointCloud2,
      topic: $(arg namespace)front_rgbd/front_rgbd/depth/points,
      marking: true,
      clearing: true,
    }

  rear_rgbd:
    {
      sensor_frame: $(arg frame)rear_rgbd_reference_frame,
      data_type: PointCloud2,
      topic: $(arg namespace)rear_rgbd/rear_rgbd/depth/points,
      marking: true,
      clearing: true,
    }

  rear_left_rgbd:
    {
      sensor_frame: $(arg frame)rear_left_rgbd_reference_frame,
      data_type: PointCloud2,
      topic: $(arg namespace)rear_left_rgbd/rear_left_rgbd/depth/points,
      marking: true,
      clearing: true,
    }

  rear_right_rgbd:
    {
      sensor_frame: $(arg frame)rear_right_rgbd_reference_frame,
      data_type: PointCloud2,
      topic: $(arg namespace)rear_right_rgbd/rear_right_rgbd/depth/points,
      marking: true,
      clearing: true,
    }

inflation_layer:
  inflation_radius: 2.0
