plugins:
    - {name: static_map_layer,    type: "costmap_2d::StaticLayer"}
    - {name: 2d_obstacles_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: 3d_obstacles_layer,  type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
    - {name: semantic_layer,     type: "costmap_2d::SemanticLayer"}
