robot_base_frame: $(arg frame)base_link

#https://github.com/inomuh/agv/blob/7c5e97311a77bd878fdaeba2b263bd6aa054db71/agv_navigation/params/agv_common.yaml
update_frequency: 5.0
publish_frequency: 5.0
footprint:
    [[0.513, 0.364], [0.513, -0.364], [-0.513, -0.364], [-0.513, 0.364]]
footprint_padding: 0.01
transform_tolerance: 0.3
robot_radius: 0.629

inflation_radius: 1.0
cost_scaling_factor: 5.0

obstacle_range: 2.5 #default = 2.5
raytrace_range: 3.0 #default = 3.0

map_type: costmap
observation_sources: scan
scan:
  {
    topic: $(arg namespace)/scan,
    sensor_frame: $(arg frame)scan_link,
    data_type: LaserScan,
    clearing: true,
    marking: true,
    inf_is_valid: true,
    max_obstacle_height: 2.0,
    min_obstacle_height: 0.0,
  }