/**:
  ros__parameters:
    analyzers:
      computers:
        analyzers:
          b1:
            contains: -b1
            path: b1
            type: diagnostic_aggregator/GenericAnalyzer
          h1:
            contains: -h1
            path: h1
            type: diagnostic_aggregator/GenericAnalyzer
          s1:
            contains: -s1
            path: s1
            type: diagnostic_aggregator/GenericAnalyzer
          t1:
            contains: -t1
            path: t1
            type: diagnostic_aggregator/GenericAnalyzer
          t2:
            contains: -t2
            path: t2
            type: diagnostic_aggregator/GenericAnalyzer
          t3:
            contains: -t3
            path: t3
            type: diagnostic_aggregator/GenericAnalyzer
        path: Computers
        type: diagnostic_aggregator/AnalyzerGroup
      io:
        analyzers:
          joystick:
            contains: joy
            path: Joystick
            type: diagnostic_aggregator/GenericAnalyzer
          light:
            contains: light
            path: Light
            type: diagnostic_aggregator/GenericAnalyzer
          sound:
            contains: sound
            path: Sound
            type: diagnostic_aggregator/GenericAnalyzer
        path: IO
        type: diagnostic_aggregator/AnalyzerGroup
      motors:
        analyzers:
          arm_left:
            contains: arm_left/
            path: Arm Left
            type: diagnostic_aggregator/GenericAnalyzer
          arm_right:
            contains: arm_right/
            path: Arm Right
            type: diagnostic_aggregator/GenericAnalyzer
          base:
            contains: base/
            path: Base
            type: diagnostic_aggregator/GenericAnalyzer
          gripper_left:
            contains: gripper_left
            path: Gripper Left
            type: diagnostic_aggregator/GenericAnalyzer
          gripper_right:
            contains: gripper_right
            path: Gripper Right
            type: diagnostic_aggregator/GenericAnalyzer
          sensorring:
            contains: sensorring/
            path: Sensorring
            type: diagnostic_aggregator/GenericAnalyzer
          torso:
            contains: torso/
            path: Torso
            type: diagnostic_aggregator/GenericAnalyzer
        path: Actuators
        type: diagnostic_aggregator/AnalyzerGroup
      safety:
        contains: safety
        path: Safety
        type: diagnostic_aggregator/GenericAnalyzer
      sensors:
        analyzers:
          battery:
            contains: bms
            path: Battery Status
            type: diagnostic_aggregator/GenericAnalyzer
          head_cam:
            contains: head_cam
            path: Head Cam
            type: diagnostic_aggregator/GenericAnalyzer
          laser_front:
            contains: laser_left
            path: Scan Left
            type: diagnostic_aggregator/GenericAnalyzer
          laser_rear:
            contains: laser_right
            path: Scan Right
            type: diagnostic_aggregator/GenericAnalyzer
          laser_top:
            contains: laser_front
            path: Scan Front
            type: diagnostic_aggregator/GenericAnalyzer
          sensorring_cam3d:
            contains: sensorring_cam3d
            path: Sensorring Cam3d
            type: diagnostic_aggregator/GenericAnalyzer
          torso_cam3d_down:
            contains: torso_cam3d_down
            path: Torso Cam3d Down
            type: diagnostic_aggregator/GenericAnalyzer
          torso_cam3d_left:
            contains: torso_cam3d_left
            path: Torso Cam3d Left
            type: diagnostic_aggregator/GenericAnalyzer
          torso_cam3d_right:
            contains: torso_cam3d_right
            path: Torso Cam3d Right
            type: diagnostic_aggregator/GenericAnalyzer
        path: Sensors
        type: diagnostic_aggregator/AnalyzerGroup
    base_path: ''
    pub_rate: 1.0
