/**:
  ros__parameters:
    accel_lim_vx: 0.5
    accel_lim_vy: 0.5
    accel_lim_w: 0.5
    decel_factor: 1.5
    decel_factor_safe: 3.5
    frequency: 100.0
    robot_feedback: 2
    speed_lim_vx: 1.0
    speed_lim_vy: 1.0
    speed_lim_w: 1.0
